document_sumarization_task:
  description: >
    Your job is to take the unstructured fax information and turn it into data that can be analyzed for {provider_name}. Please analyze the incoming fax document and extract all relevant information. You work for {provider_name}, so you know that these faxes are always being sent to them.
    Identify document type, key sections, and core patient/provider information. \n\n
    fax_data: {data}
  expected_output: >
    A simple text based summary of the document structure and key details. It is ok to provide a lot of information here, as the next agent will be responsible for parsing it.
    Key elements to extract:
    - Core patient demographics (ex. name, DOB, height, weight , etc..)
    - Referral reason including symptoms, diagnosis, or other relevant information (summary)
    - Referring provider information including practice information such as name, address, fax number and phone number
    - Prior testing done (all details) and if the testing is included in the fax
    - Any other relevant information that may be useful for the next agent
  agent: document_summarizer

medical_analysis_task:
  description: >
    Evaluate the clinical appropriateness of the referral based on:
    - Prior testing and procedures
    - Current symptoms
    - Medical necessity for neurology consultation
    - If the patient has been seen by a neurologist before or had a NCS/EMG done in the past you should mark this as a conflicting referral.
  expected_output: >
    A clinical analysis brief sumary containing:
    - Appropriateness score
    - Prior testing identification
    - If Conflicting referrals are present
    - Recommendation (schedule/review/reject)
    - Other recommendations or notes
  agent: medical_analyzer

alignment_task:
  description: >
    Cross-validate all extracted information and analysis results.
    Ensure clinical consistency across all fields.
    Generate final structured output for the main system.
  expected_output: >
    Confirm the final structured output is accurate and consistent with the original fax document and include potential conflicting referrals if present in the previous analysis.
    A validated JSON payload containing the following structure:
    data: {
      patientName: <string>,
      patientDOB: <string>,
      referringProvider: <string>,
      referringPractice: <string>,
      pastDiagnoses: <{ 
        name<string>, ICD10<string|null>, date<string|null>
      }>[],
      appropriateReferral: <boolean>,
      appropriatenessScore: <float> (1-10),
      conflictingReferralsPresent: <boolean>,
      conflictingReferrals: <string[]> | null,
      hpi: <string>,
      currentMedications: <{name<string>, dose<string>, frequency<string>}[]>,
      allergies: <{name<string>, reaction<string>}[]>,
      recommendedAction: <string> (schedule/review/reject),
      recommendedAppointmentType: <oneof {possible_referral_reasons}>,
      recentImaging: <{name<string>, date<string>}[]> | null,
      otherRecommendations: <string>[] | null 
    }
  agent: alignment_agent
  context:
    - document_sumarization_task
    - medical_analysis_task
